name: DAMAP Instances

on:
  push:
    branches: [ main, "1-proposal-structure" ] # just temporary testing
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: false
        default: 'main'
      instance:
        type: choice
        description: 'Choose the backend instance'
        options:
        - both
        - MUG
        - TUG
        required: false
        default: both

env:
  REGISTRY: ghcr.io

jobs:
  build-backend-instances:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: ${{ 
          (github.event.inputs.instance == 'both' || github.event.inputs.instance == '') && fromJSON('["MUG", "TUG"]') ||
          fromJSON(format('["{0}"]', github.event.inputs.instance))}}
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      run: |
        BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
        git clone https://github.com/${{ github.repository }}.git .
        git checkout $BRANCH

    - name: Extract backend instance 
      run: |
        chmod +x scripts/extract-instances.sh
        ./scripts/extract-instances.sh backend ${{ matrix.instance }}

    - name: Log in to container registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

    - name: Determine Docker tag
      run: |
        BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
        echo "DOCKER_TAG=$BRANCH" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="${{ env.REGISTRY }}/${REPO_NAME}-backend-${{ matrix.instance }}"
        IMAGE_TAG="${IMAGE_NAME}:${{ env.DOCKER_TAG }}"
        IMAGE_SHA="${IMAGE_NAME}:${{ github.sha }}"
        
        docker build \
          --build-arg INSTANCE_TYPE=backend \
          --build-arg INSTANCE_NAME=${{ matrix.instance }} \
          --tag "${IMAGE_TAG}" \
          --tag "${IMAGE_SHA}" \
          .

    - name: Push Docker image
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="${{ env.REGISTRY }}/${REPO_NAME}-backend-${{ matrix.instance }}"
        docker push "${IMAGE_NAME}:${{ env.DOCKER_TAG }}"
        docker push "${IMAGE_NAME}:${{ github.sha }}" 